language: julia
os:
  - linux
  - osx
julia:
  - 1.2
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: true
after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("NewsAPI")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'